import 'package:flutter/widgets.dart';

const supportedAppLocales = <Locale>[Locale('tr'), Locale('en')];

class AppStrings {
  const AppStrings(this.locale);

  final Locale locale;
  bool get isTurkish => locale.languageCode == 'tr';

  static AppStrings of(BuildContext context) => AppStrings(
    AppLanguageScope.maybeOf(context)?.locale ?? const Locale('tr'),
  );

  static const _tr = <String, String>{
    'common.close': 'Kapat',
    'common.language': 'Dil',
    'common.loading': 'Yükleniyor…',
    'language.turkish': 'Türkçe',
    'language.english': 'English',
    'login.subtitle': 'Devam etmek için giriş yap.',
    'login.email': 'E-posta',
    'login.password': 'Şifre',
    'login.submit': 'Giriş yap',
    'login.wait': 'Giriş yapılıyor…',
    'planner.previousDay': 'Önceki gün',
    'planner.nextDay': 'Sonraki gün',
    'planner.previousMonth': 'Önceki ay',
    'planner.nextMonth': 'Sonraki ay',
    'planner.today': 'Bugün',
    'planner.boards': 'Panolar',
    'planner.readOnly': 'Salt okunur',
    'planner.manageBoards': 'Pano ve paylaşım',
    'planner.searchCards': 'Kartlarda ara',
    'planner.filterCards': 'Kartları filtrele',
    'planner.fastNavigation': 'Hızlı gezme',
    'planner.refresh': 'Yenile',
    'planner.sync': 'Senkronize et',
    'planner.archiveTrash': 'Arşiv ve Çöp Kutusu',
    'planner.templates': 'Şablonlar',
    'planner.transfer': 'İçe / Dışa Aktar',
    'planner.activity': 'Etkinlik geçmişi',
    'planner.logout': 'Çıkış',
    'planner.accessibility': 'Erişilebilirlik',
    'accessibility.title': 'Erişilebilirlik',
    'accessibility.motion': 'Hareket',
    'accessibility.motion.system': 'Sistem ayarını kullan',
    'accessibility.motion.reduce': 'Hareketi azalt',
    'accessibility.motion.full': 'Tam hareket',
    'accessibility.textDensity': 'Metin ve arayüz yoğunluğu',
    'accessibility.density.compact': 'Kompakt',
    'accessibility.density.standard': 'Standart',
    'accessibility.density.comfortable': 'Büyük ve rahat',
    'accessibility.hint': 'Değişiklikler anında uygulanır ve bu cihazda saklanır.',
    'card.inspect': 'İncele',
    'card.untitled': '(başlıksız)',
    'card.tags': 'Etiketler',
    'card.status': 'Durum',
    'card.done': 'Yapıldı',
    'card.pending': 'Bekliyor',
    'card.priority': 'Öncelik',
    'card.deadline': 'Son tarih',
    'card.overdue': 'Gecikti',
    'card.none': 'Yok',
    'card.reminder': 'Hatırlatma',
    'card.source': 'Kaynak',
    'card.habitGenerated': 'Davranıştan üretildi',
    'card.template': 'Şablon',
    'card.templateLinked': 'Bağlı · değiştirilirse ayrılır',
    'card.image': 'Görsel',
    'card.imageFailed': 'Görsel yüklenemedi',
    'card.history': 'Geçmiş',
    'card.archive': 'Arşivle',
    'card.duplicate': 'Çoğalt',
    'card.makeTemplate': 'Şablon yap',
    'card.trash': 'Çöpe at',
    'card.edit': 'Düzenle',
    'priority.none': 'Yok',
    'priority.low': 'Düşük',
    'priority.medium': 'Orta',
    'priority.high': 'Yüksek',
    'priority.urgent': 'Acil',
    'view.week': 'Hafta',
    'view.month': 'Ay',
    'view.agenda': 'Ajanda',
    'view.completed': 'Tamamlananlar',
    'activity.title': 'Etkinlik geçmişi',
    'activity.empty': 'Henüz etkinlik yok.',
    'activity.failed': 'Etkinlik geçmişi yüklenemedi.',
    'activity.loadOlder': 'Daha eski etkinlikleri yükle',
    'activity.deletedUser': 'Silinmiş kullanıcı',
    'activity.untitled': 'Başlıksız kart',
    'activity.orderChanged': 'Kart sırası değiştirildi',
    'activity.created': 'kartı oluşturdu',
    'activity.updated': 'kartı düzenledi',
    'activity.moved': 'kartı taşıdı',
    'activity.completed': 'kartı tamamladı',
    'activity.reopened': 'kartı yeniden açtı',
    'activity.archived': 'kartı arşivledi',
    'activity.trashed': 'kartı çöpe attı',
    'activity.restored': 'kartı geri yükledi',
    'activity.deleted': 'kartı kalıcı olarak sildi',
    'activity.duplicated': 'kartı çoğalttı',
    'field.day': 'gün',
    'field.title': 'başlık',
    'field.note': 'not',
    'field.startTime': 'başlangıç',
    'field.endTime': 'bitiş',
    'field.color': 'renk',
    'field.done': 'durum',
    'field.checklist': 'checklist',
    'field.priority': 'öncelik',
    'field.deadlineAt': 'son tarih',
    'field.tags': 'etiketler',
  };

  static const _en = <String, String>{
    'common.close': 'Close',
    'common.language': 'Language',
    'common.loading': 'Loading…',
    'language.turkish': 'Türkçe',
    'language.english': 'English',
    'login.subtitle': 'Sign in to continue.',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Sign in',
    'login.wait': 'Signing in…',
    'planner.previousDay': 'Previous day',
    'planner.nextDay': 'Next day',
    'planner.previousMonth': 'Previous month',
    'planner.nextMonth': 'Next month',
    'planner.today': 'Today',
    'planner.boards': 'Boards',
    'planner.readOnly': 'View only',
    'planner.manageBoards': 'Boards and sharing',
    'planner.searchCards': 'Search cards',
    'planner.filterCards': 'Filter cards',
    'planner.fastNavigation': 'Quick navigation',
    'planner.refresh': 'Refresh',
    'planner.sync': 'Sync now',
    'planner.archiveTrash': 'Archive and Trash',
    'planner.templates': 'Templates',
    'planner.transfer': 'Import / Export',
    'planner.activity': 'Activity history',
    'planner.logout': 'Sign out',
    'planner.accessibility': 'Accessibility',
    'accessibility.title': 'Accessibility',
    'accessibility.motion': 'Motion',
    'accessibility.motion.system': 'Use system setting',
    'accessibility.motion.reduce': 'Reduce motion',
    'accessibility.motion.full': 'Full motion',
    'accessibility.textDensity': 'Text and interface density',
    'accessibility.density.compact': 'Compact',
    'accessibility.density.standard': 'Standard',
    'accessibility.density.comfortable': 'Large and comfortable',
    'accessibility.hint': 'Changes apply immediately and are stored on this device.',
    'card.inspect': 'View card',
    'card.untitled': '(untitled)',
    'card.tags': 'Tags',
    'card.status': 'Status',
    'card.done': 'Completed',
    'card.pending': 'Pending',
    'card.priority': 'Priority',
    'card.deadline': 'Deadline',
    'card.overdue': 'Overdue',
    'card.none': 'None',
    'card.reminder': 'Reminder',
    'card.source': 'Source',
    'card.habitGenerated': 'Generated from a habit',
    'card.template': 'Template',
    'card.templateLinked': 'Linked · editing detaches it',
    'card.image': 'Image',
    'card.imageFailed': 'Could not load image',
    'card.history': 'History',
    'card.archive': 'Archive',
    'card.duplicate': 'Duplicate',
    'card.makeTemplate': 'Save as template',
    'card.trash': 'Move to trash',
    'card.edit': 'Edit',
    'priority.none': 'None',
    'priority.low': 'Low',
    'priority.medium': 'Medium',
    'priority.high': 'High',
    'priority.urgent': 'Urgent',
    'view.week': 'Week',
    'view.month': 'Month',
    'view.agenda': 'Agenda',
    'view.completed': 'Completed',
    'activity.title': 'Activity history',
    'activity.empty': 'No activity yet.',
    'activity.failed': 'Could not load activity history.',
    'activity.loadOlder': 'Load older activity',
    'activity.deletedUser': 'Deleted user',
    'activity.untitled': 'Untitled card',
    'activity.orderChanged': 'Card order changed',
    'activity.created': 'created the card',
    'activity.updated': 'edited the card',
    'activity.moved': 'moved the card',
    'activity.completed': 'completed the card',
    'activity.reopened': 'reopened the card',
    'activity.archived': 'archived the card',
    'activity.trashed': 'moved the card to trash',
    'activity.restored': 'restored the card',
    'activity.deleted': 'permanently deleted the card',
    'activity.duplicated': 'duplicated the card',
    'field.day': 'day',
    'field.title': 'title',
    'field.note': 'note',
    'field.startTime': 'start time',
    'field.endTime': 'end time',
    'field.color': 'color',
    'field.done': 'status',
    'field.checklist': 'checklist',
    'field.priority': 'priority',
    'field.deadlineAt': 'deadline',
    'field.tags': 'tags',
  };

  String text(String key) => (isTurkish ? _tr : _en)[key] ?? _tr[key] ?? key;
}

class AppLanguageScope extends InheritedWidget {
  const AppLanguageScope({
    super.key,
    required this.locale,
    required super.child,
  });

  final Locale locale;

  static AppLanguageScope? maybeOf(BuildContext context) =>
      context.dependOnInheritedWidgetOfExactType<AppLanguageScope>();

  @override
  bool updateShouldNotify(AppLanguageScope oldWidget) => locale != oldWidget.locale;
}

extension AppStringsContext on BuildContext {
  AppStrings get strings => AppStrings.of(this);
}
